name: Test Access

on:
  pull_request:
    branches:
      - main

jobs:
    Access-and-Pull:
        runs-on: ubuntu-latest
        steps:
            - name: SSH
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.APP_USER }}
                key: ${{ secrets.KEY }}
                port: ${{ secrets.PORT }}
                script: |
                  eval $(ssh-agent -s)
                  echo "${{secrets.GIT_KEY}}" | tr -d '\r' | ssh-add - <<< "${{secrets.PASSPHRASE}}"
                  ssh-add -l
                  ls -la
                  cd ${{ secrets.WORK_DIR }}
                  git pull
