name: Test Access

on:
  pull_request:
    branches:
      - main

jobs:
    Access-and-Pull:
        runs-on: ubuntu-latest
        steps:
            - name: SSH
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.KEY }}
                port: ${{ secrets.PORT }}
                    
                script: |
                     ls -la
                     cd ${{secrets.WORK_DIR}}
                     su mngr
                     git pull
